### ISSUE TITLE
It seems OIT lost Anti-aliasing?

### ISSUE THREAD

**Issue by ldbfrank** [endavid/VidEngine#8]

**Comment by ldbfrank** [comment]
Nobody nobody here? nobody nobody here?

**Comment by ldbfrank** [comment]
莫有人？

**Comment by ldbfrank** [comment]
来人呐！拉出去砍了！

**Comment by endavid** [comment]
Sorry, I haven't configured e-mail notifications in Github, so it took me a while to realize you posted these issues. Thanks for testing VidEngine. I haven't set up antialiasing in VidEngine yet, so rather than an issue, this should be a feature request. I'm closing it, since it affects everything, not just OIT.
