### ISSUE TITLE
How to apply .one to .oneMinusSourceAlpha for translucent objects?

### ISSUE THREAD

**Issue by ldbfrank** [endavid/VidEngine#9]
Hi,
I seems all translucent objects in VidEngine are .zero to .minusSourceAlpha, I try to modify to .one to .oneMinusSourceAlpha, but it not work.
Would you please tell me where to modify to do that?
Thanks.

**Comment by endavid** [comment]
VidEngine at the moment uses a method called Weight-Blended Order Independent Transparency for rendering transparent objects in 3D. You can read about it here: http://endavid.com/index.php?entry=76 
At the moment, the shader assumes that the textures do not have premultiplied alpha. If your textures have premultiplied alpha, the only way to fix the rendering at the moment is by changing the shader. In `Transparency.metal`, comment out this line from `passFragmentOIT`:

    // if texture has no premultiplied alpha, apply this,
    color.rgb *= color.a;

The blending of the render targets must not be changed because it's applying the Weight-Blended OIT math formula.

I have a plugin with traditional transparency, but I didn't submit it because it requires sorting the primitives and I think it's slow. I would like to better the OIT, rather than pursuing two methods simultaneously.

However, if you are talking about 2D objects, I should use traditional transparency for that. But the 2D plugin is not fully developed yet. If you want to experiment with it, it is setup in `Primitive2DPlugin`, in the `createPipelineDescriptor` method. It is currently set as,

        desc.colorAttachments[0].sourceRGBBlendFactor = .sourceAlpha
        desc.colorAttachments[0].destinationRGBBlendFactor = .oneMinusSourceAlpha

Feel free to experiment with it 👍

**Comment by ldbfrank** [comment]
Got it，thanks. ^_^

发自我的iPhone


------------------ Original ------------------
